# Generated by Django 5.2.15 on 2026-07-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(blank=True, choices=[('na', 'North America'), ('eu', 'Europe'), ('ap', 'Asia Pacific'), ('kr', 'Korea'), ('latam', 'Latin America'), ('br', 'Brazil')], max_length=8)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('comm_preference', models.CharField(blank=True, choices=[('voice', 'Voice only'), ('text', 'Text only'), ('either', 'Either')], max_length=8)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='profiles.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRoleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('igl', 'IGL'), ('entry', 'Entry Fragger'), ('support', 'Support'), ('duelist_main', 'Duelist Main'), ('controller_main', 'Controller Main'), ('initiator_main', 'Initiator Main'), ('sentinel_main', 'Sentinel Main'), ('flex', 'Flex')], max_length=24)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_tags', to='profiles.playerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'role'), name='uniq_profile_role')],
            },
        ),
    ]
