# Generated by Django 5.2.15 on 2026-07-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterBackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('total', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('ingested', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncounterMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('map_name', models.CharField(blank=True, default='', max_length=64)),
                ('mode', models.CharField(blank=True, default='', max_length=32)),
                ('season_name', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EncounterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('tag', models.CharField(blank=True, default='', max_length=16)),
                ('team_id', models.CharField(blank=True, default='', max_length=8)),
                ('party_id', models.CharField(blank=True, default='', max_length=64)),
                ('agent', models.CharField(blank=True, default='', max_length=32)),
                ('agent_image', models.CharField(blank=True, default='', max_length=200)),
                ('won', models.BooleanField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tracker.encountermatch')),
            ],
            options={
                'indexes': [models.Index(fields=['puuid', 'team_id'], name='tracker_enc_puuid_5bc9c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'puuid'), name='unique_encounter_match_player')],
            },
        ),
    ]
