# Generated by Django 5.2.16 on 2026-07-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_encounterbackfilljob_encountermatch_encounterplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterplayer',
            name='team_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
