# Generated by Django 5.2.15 on 2026-07-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiotAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('riot_game_name', models.CharField(max_length=16)),
                ('riot_tag_line', models.CharField(max_length=8)),
                ('puuid', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=8)),
                ('account_level', models.IntegerField(blank=True, null=True)),
                ('current_tier', models.CharField(blank=True, choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('ascendant', 'Ascendant'), ('immortal', 'Immortal'), ('radiant', 'Radiant')], max_length=16)),
                ('current_rr', models.IntegerField(blank=True, null=True)),
                ('peak_tier', models.CharField(blank=True, choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('ascendant', 'Ascendant'), ('immortal', 'Immortal'), ('radiant', 'Radiant')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('manual_review', 'Manual review requested'), ('rejected', 'Rejected'), ('expired', 'Verification window expired')], default='pending', max_length=16)),
                ('verification_window_start', models.DateTimeField(blank=True, null=True)),
                ('verification_window_end', models.DateTimeField(blank=True, null=True)),
                ('verification_match_id', models.CharField(blank=True, max_length=64)),
                ('manual_review_screenshot', models.FileField(blank=True, upload_to='riot-verification/')),
                ('last_rank_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riot_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'verified')), fields=('riot_game_name', 'riot_tag_line'), name='uniq_verified_riot_id')],
            },
        ),
    ]
