# Generated by Django 5.2.15 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riotaccountlink',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riotaccountlink',
            name='peak_division',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
