# Generated by Django 5.2.15 on 2026-07-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('discord', 'Discord')], max_length=16)),
                ('provider_uid', models.CharField(max_length=128)),
                ('discord_username', models.CharField(blank=True, max_length=64)),
                ('discord_avatar_hash', models.CharField(blank=True, max_length=128)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uniq_provider_account'), models.UniqueConstraint(fields=('user', 'provider'), name='uniq_user_provider')],
            },
        ),
    ]
