# Generated by Django 5.2.15 on 2026-07-04 05:51

import apps.matchmaking.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('lf_fifth', 'Looking for 5th'), ('lf_duo', 'Looking for duo'), ('lf_stack', 'Building a stack'), ('lf_group_to_join', 'Looking to join a group')], max_length=24)),
                ('region', models.CharField(choices=[('na', 'North America'), ('eu', 'Europe'), ('ap', 'Asia Pacific'), ('kr', 'Korea'), ('latam', 'Latin America'), ('br', 'Brazil')], max_length=8)),
                ('party_size_current', models.PositiveSmallIntegerField(default=1)),
                ('party_size_target', models.PositiveSmallIntegerField()),
                ('rank_min', models.CharField(blank=True, choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('ascendant', 'Ascendant'), ('immortal', 'Immortal'), ('radiant', 'Radiant')], max_length=16)),
                ('rank_max', models.CharField(blank=True, choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('ascendant', 'Ascendant'), ('immortal', 'Immortal'), ('radiant', 'Radiant')], max_length=16)),
                ('roles_needed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('igl', 'IGL'), ('entry', 'Entry Fragger'), ('support', 'Support'), ('duelist_main', 'Duelist Main'), ('controller_main', 'Controller Main'), ('initiator_main', 'Initiator Main'), ('sentinel_main', 'Sentinel Main'), ('flex', 'Flex')], max_length=24), blank=True, default=list, size=None)),
                ('comm_preference', models.CharField(choices=[('voice', 'Voice only'), ('text', 'Text only'), ('either', 'Either')], default='either', max_length=8)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('expires_at', models.DateTimeField(default=apps.matchmaking.models.default_listing_expiry)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_memberships', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='matchmaking.partylisting')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='matchmaking.partylisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partylisting',
            index=models.Index(fields=['status', 'region', '-created_at'], name='matchmaking_status_0db0d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingmember',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='uniq_listing_member'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('listing', 'requester'), name='uniq_pending_join_request'),
        ),
    ]
